/*
 * This Spock specification was generated by the Gradle 'init' task.
 */
package com.exsoinn.spring.practice

import spock.lang.Specification

class SpringPracticeApplicationTest extends Specification {
    /*def "application has a greeting"() {
        setup:
        def app = new SpringPracticeApplication()

        when:
        def result = app.greeting

        then:
        result != null
    }*/
}
